[server]
host = 127.0.0.1
port = 6969
debug = false

[playwright]
browser = chromium
channel = chromium
# executable = /usr/bin/google-chrome-stable

[proxy]
# proxy = socks5://127.0.0.1:7898

[rate]
ms_per_req = 10000
